-- 코드를 입력하세요
SELECT TITLE, B.BOARD_ID,REPLY_ID, R.WRITER_ID, R.CONTENTS, R.CREATED_DATE 
from USED_GOODS_REPLY R join USED_GOODS_BOARD B on B.BOARD_ID=R.BOARD_ID
where year(B.CREATED_DATE)=2022 and month(B.CREATED_DATE)=10
order by R.CREATED_DATE, TITLE;